# pnpm-workspace.yaml
packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  esbuild: set this to true or false
  unrs-resolver: set this to true or false

# Allow these dependencies to run build scripts
onlyBuiltDependencies:
  - 'esbuild'
  - 'unrs-resolver'
